### ISSUE TITLE
Any training trajectories reported in the paper?

### ISSUE THREAD

**Issue by JasonQSY** [SudeepDasari/data4robotics#3]
Hi,

Thanks for your great work! I'm interested in reproducing the simulated benchmarks reported in the paper. I've successfully setup the python environment and pretrained vit models. However, it looks like there are no provided training trajectories so that I can reproduce the number in the paper.

Is it possible to release them? Thanks!

**Comment by SudeepDasari** [comment]
So this repo was used for the real world experiments in the paper. You'd need to collect ~50 expert demos to reproduce it on your own robot.

However, if you just want to reproduce the simulation numbers, you can combine our representations with the sawyer environments/data from [robomimic](https://robomimic.github.io/) and the [vc-1 meta-world envs](https://github.com/facebookresearch/eai-vc).
