### ISSUE TITLE
HRP paper with Appendix

### ISSUE THREAD

**Issue by Kadruschki** [SudeepDasari/data4robotics#4]
Hi,

in the paper "HRP: Human Affordances for Robotic Pre-Training" you referred to the Appendix a few times. I wanted to check it out, but I couldn't find an upload of the paper where the Appendix is included. 

Is it possible to upload it somewhere? Thanks!

**Comment by SudeepDasari** [comment]
Sorry, we will fix the website ASAP!

For now, I've attached the verison with appendix to this comment [2024_hrp_rss.pdf](https://github.com/user-attachments/files/16383464/2024_hrp_rss.pdf)
