### ISSUE TITLE
affordance prediction with pretrained model

### ISSUE THREAD

**Issue by Tom-Huang** [SudeepDasari/data4robotics#6]
@SudeepDasari Dear authors of the paper, thank you so much for your great work and the release of the code. I wonder if it is possible to use the pre-trained model to predict affordance from the image like in the VRB paper. Could you also provide the code and weight for that? Thank you so much!

**Comment by mohanksriram** [comment]
Hi Tom, Please use this [script](https://github.com/SudeepDasari/data4robotics/blob/hrp_release/examples/explore_attention_maps.py) on the hrp_release branch for attention visualization!

Example usage:
```
python examples/explore_attention_maps.py --vit_model_name={VC1_hrp|SOUP_1M_DH|Any vit_base/hrp model} --img_path={path/to/image.png}
```
