### ISSUE TITLE
How to fine-tune DiT-Block Policy with your own data

### ISSUE THREAD

**Issue by le-wei** [SudeepDasari/data4robotics#9]
"Hello, thank you very much for the work you've done. If I want to test the DiT-Block Policy you proposed, which command should I run? Also, does the first command support the **ac_chunk** parameter? Thank you."

- Gaussian Mixture Model bc-policy with SOUP representations
python finetune.py exp_name=test agent.features.restore_path=/path/to/SOUP_1M_DH.pth buffer_path=/data/path/buffer.pkl

-  Diffusion Policy (U-Net head) w/ HRP representations
python finetune.py exp_name=test agent=diffusion_unet task=end_effector_r6 agent/features=vit_base agent.features.restore_path=/path/to/IN_hrp.pth buffer_path=/data/path/buffer.pkl trainer=bc_cos_sched ac_chunk=16

-  Diffusion Transformer (DiT head) w/ ResNet tokenizer
python finetune.py exp_name=test agent=diffusion task=end_effector_r6 agent/features=resnet_gn agent.features.restore_path=/pat/to/resnet18/IN_1M_resnet18.pth  trainer=bc_cos_sched ac_chunk=100

**Comment by SudeepDasari** [comment]
The last command would be the one you need to run. Though, you'd need to convert the data into our format first ([link](https://github.com/AGI-Labs/r2d2_to_robobuf)). We have a more detailed writeup at our repo fork [here](https://github.com/SudeepDasari/dit-policy).

And, yes `ac_chunk` is supported on all of the commands. Read more about how hydra hyper-parameters works [here](https://hydra.cc/).
